import { mkdir, readFile, readdir, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";

import { isValidId } from "~/lib/ids";
import type { Orientation } from "~/features/store/types";
import type { TemplateConfig } from "~/features/templates/types";

/**
 * Where a browser's uploads and generated assets live for the lifetime of its
 * session cookie. There is no database and no account: a workspace is a
 * directory, and it is swept once it goes stale.
 */
const DATA_DIR = process.env.APPLAUNCHKIT_DATA_DIR
  ? path.resolve(process.env.APPLAUNCHKIT_DATA_DIR)
  : path.join(process.cwd(), ".data");

const WORKSPACES_DIR = path.join(DATA_DIR, "workspaces");
export const WORKSPACE_TTL_MS = 7 * 24 * 60 * 60 * 1000;

export type StoredScreenshot = {
  id: string;
  fileName: string;
  extension: string;
  width: number;
  height: number;
  format: string;
  fileSize: number;
  orientation: string;
  caption: string;
  sortOrder: number;
};

export type StoredAsset = {
  id: string;
  screenshotId: string;
  targetId: string;
  platform: string;
  deviceType: string;
  orientation: Orientation;
  templateKey: string;
  width: number;
  height: number;
  fileSize: number;
  createdAt: string;
};

export type Workspace = {
  version: 1;
  createdAt: string;
  updatedAt: string;
  screenshots: StoredScreenshot[];
  assets: StoredAsset[];
  /** Last styling used, so the editor reopens where the user left off. */
  style: Partial<TemplateConfig>;
};

function emptyWorkspace(): Workspace {
  const now = new Date().toISOString();
  return {
    version: 1,
    createdAt: now,
    updatedAt: now,
    screenshots: [],
    assets: [],
    style: {},
  };
}

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

function workspaceDir(sessionId: string): string {
  if (!isValidId(sessionId)) {
    throw new Error("Invalid workspace id.");
  }
  return path.join(WORKSPACES_DIR, sessionId);
}

function manifestPath(sessionId: string): string {
  return path.join(workspaceDir(sessionId), "workspace.json");
}

/** Ids are generated by `crypto.randomUUID`, so they are validated the same way. */
function assertId(id: string): string {
  if (!isValidId(id)) throw new Error("Invalid file id.");
  return id;
}

function originalPath(
  sessionId: string,
  screenshotId: string,
  extension: string,
): string {
  const safeExtension = /^[a-z]{2,5}$/.test(extension) ? extension : "bin";
  return path.join(
    workspaceDir(sessionId),
    "originals",
    `${assertId(screenshotId)}.${safeExtension}`,
  );
}

function generatedPath(sessionId: string, assetId: string): string {
  return path.join(
    workspaceDir(sessionId),
    "generated",
    `${assertId(assetId)}.png`,
  );
}

// ---------------------------------------------------------------------------
// Manifest
// ---------------------------------------------------------------------------

const locks = new Map<string, Promise<unknown>>();

/**
 * Serialises manifest read-modify-write per workspace. Two uploads landing at
 * once would otherwise each write a manifest built from the same stale copy,
 * losing one of them.
 */
function withLock<T>(sessionId: string, fn: () => Promise<T>): Promise<T> {
  const previous = locks.get(sessionId) ?? Promise.resolve();
  const next = previous.then(fn, fn);
  locks.set(
    sessionId,
    next.catch(() => {}),
  );
  return next;
}

export async function readWorkspace(sessionId: string): Promise<Workspace> {
  try {
    const raw = await readFile(manifestPath(sessionId), "utf8");
    const parsed = JSON.parse(raw) as Workspace;
    if (parsed.version !== 1) return emptyWorkspace();
    return {
      ...emptyWorkspace(),
      ...parsed,
      screenshots: parsed.screenshots ?? [],
      assets: parsed.assets ?? [],
    };
  } catch {
    // Missing or unreadable manifest: an empty workspace is the right answer.
    return emptyWorkspace();
  }
}

/** Applies `mutate` to the manifest under the workspace lock. */
export async function updateWorkspace<T>(
  sessionId: string,
  mutate: (workspace: Workspace) => T | Promise<T>,
): Promise<{ workspace: Workspace; result: T }> {
  return withLock(sessionId, async () => {
    const workspace = await readWorkspace(sessionId);
    const result = await mutate(workspace);
    workspace.updatedAt = new Date().toISOString();

    await mkdir(workspaceDir(sessionId), { recursive: true });
    await writeFile(
      manifestPath(sessionId),
      JSON.stringify(workspace, null, 2),
      "utf8",
    );
    return { workspace, result };
  });
}

// ---------------------------------------------------------------------------
// Files
// ---------------------------------------------------------------------------

export async function writeOriginal(
  sessionId: string,
  screenshotId: string,
  extension: string,
  body: Buffer,
): Promise<void> {
  const target = originalPath(sessionId, screenshotId, extension);
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, body);
}

export async function readOriginal(
  sessionId: string,
  screenshot: Pick<StoredScreenshot, "id" | "extension">,
): Promise<Buffer> {
  return readFile(originalPath(sessionId, screenshot.id, screenshot.extension));
}

export async function writeGenerated(
  sessionId: string,
  assetId: string,
  body: Buffer,
): Promise<void> {
  const target = generatedPath(sessionId, assetId);
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, body);
}

export async function readGenerated(
  sessionId: string,
  assetId: string,
): Promise<Buffer> {
  return readFile(generatedPath(sessionId, assetId));
}

export async function removeOriginal(
  sessionId: string,
  screenshot: Pick<StoredScreenshot, "id" | "extension">,
): Promise<void> {
  await rm(originalPath(sessionId, screenshot.id, screenshot.extension), {
    force: true,
  });
}

export async function removeGenerated(
  sessionId: string,
  assetId: string,
): Promise<void> {
  await rm(generatedPath(sessionId, assetId), { force: true });
}

export async function removeWorkspace(sessionId: string): Promise<void> {
  await rm(workspaceDir(sessionId), { recursive: true, force: true });
}

// ---------------------------------------------------------------------------
// Cleanup
// ---------------------------------------------------------------------------

/**
 * Deletes workspaces untouched for longer than the TTL. Nothing here is meant
 * to be permanent, and uploads are people's unreleased screenshots.
 */
export async function sweepExpiredWorkspaces(
  ttlMs = WORKSPACE_TTL_MS,
): Promise<number> {
  let removed = 0;

  let entries: string[];
  try {
    entries = await readdir(WORKSPACES_DIR);
  } catch {
    return 0;
  }

  const cutoff = Date.now() - ttlMs;

  for (const entry of entries) {
    if (!isValidId(entry)) continue;
    try {
      const info = await stat(path.join(WORKSPACES_DIR, entry));
      if (info.mtimeMs < cutoff) {
        await removeWorkspace(entry);
        removed += 1;
      }
    } catch {
      // Raced with another sweep or a delete; nothing to do.
    }
  }

  return removed;
}
